services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile 
    image: sylvester1215/rms-docker-img:latest
    container_name: rms-docker-container-project
    ports:
      - "5050:5050"