# services:
#   build-rms:
#     build:
#       context: .
#       dockerfile: Dockerfile 
#     image: sylvester1215/rms-docker-img:v1
#     container_name: rms-docker-container-project
#     ports:
#       - "8000:5050"
# -----------------------------------------------------------------------
# version: '3'

# services:
#   build-rms:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: sylvester1215/rms-docker-img:v1
#     container_name: rms-docker-container-project
#     ports:
#       - "8000:5050"   # Expose your app's port to the host

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     ports:
#       - "9090:9090"  # Expose Prometheus web UI
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     depends_on:
#       - build-rms

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3000:3000"  # Expose Grafana UI to localhost:3000
#     environment:
#       GF_SECURITY_ADMIN_PASSWORD: "admin"  # Set the admin password for Grafana
#     depends_on:
#       - prometheus

version: "3.8"
services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: sylvester1215/rms-docker-img:v1
    container_name: rms-docker-container-project
    ports:
      - "8000:5050"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - build-rms

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: