services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile 
    image: sylvester1215/rms-docker-img-project:v2
    container_name: rms-docker-container-project
    ports:
      - "8000:5050" 