name: Automatic Testing for Acrochef App 

on: 
  push: 
      branches: 
          - main # Workflow will be triggered whenever there is a push in main branch 
jobs: 
  test: 
      runs-on: ubuntu-latest 
        
      steps:
      - name: Checkout code from GitHub Repo 
        uses: actions/checkout@v3 
        
      - name: Setup Node.js in Ubuntu 
        uses: actions/setup-node@v3 
        with: 
          node-version: 18 
        
      - name: Install dependencies for based on package.json 
        run: npm install 
        
      - name: Run tests in "tests" folder 
        run: npm run backend-test
        
      - name: Instrument the frontend code 
        run: npm run build-frontend && node npm-scripts/copy-code-to-instrumented-directory.mjs && npx nyc instrument dist instrumented
        
      - name: Run the frontend test cases 
        run: npm run frontend-instrument && node npm-scripts/remove-nyc-output-directory.mjs && nyc --nycrc-path .nycrc-frontend cypress run
